@MonkeyApp1_HostAddress = https://motzmonkeys.azurewebsites.net/

Get {{MonkeyApp1_HostAddress}}/api/Monkey/

###

Get {{MonkeyApp1_HostAddress}}/api/Monkey/2

###

GET {{MonkeyApp1_HostAddress}}/api/continents

###

POST {{MonkeyApp1_HostAddress}}/api/continents
Content-Type: application/json

{
  "Id": 1,
  "name":"North America"
}

###

DELETE {{MonkeyApp1_HostAddress}}/api/continents/2

###
